runtime: nodejs18

handlers:
  - url: /static
    static_dir: dist/hacks-website

  - url: /assets
    static_dir: dist/hacks-website/assets

  - url: /(.*\.js)
    static_files: dist/hacks-website/\1
    upload: dist/hacks-website/(.*\.js)
    mime_type: application/javascript

  - url: /(.*\.css)
    static_files: dist/hacks-website/\1
    upload: dist/hacks-website/(.*\.css)
    mime_type: text/css

  - url: /(.*\.(png|jpg|gif|ico))
    static_files: dist/hacks-website/\1
    upload: dist/hacks-website/(.*\.(png|jpg|gif|ico))
    mime_type: image/png

  - url: /(.*)
    static_files: dist/hacks-website/index.html
    upload: dist/hacks-website/index.html
    secure: always