runtime: nodejs18

handlers:
  - url: /static
    static_dir: dist/hacks-website

  - url: /assets
    static_dir: dist/hacks-website/assets

  - url: /(.*)
    static_files: dist/hacks-website/index.html
    upload: dist/hacks-website/index.html
    secure: always